#docker run -i -t -d --name=bomonti node:16-slim node index.js

version: '3.9'

services:
  bomonti:
    image: nozich/nozich:latest
    user: nozich:nozich
    container_name: bomonti-${ENV}
    hostname: bomonti-${ENV}
    network_mode: bridge
    ports:
      - ${PORT}:${PORT}
      - ${PORT_WS}:${PORT_WS}
    restart: always
    env_file:
      - .env
    environment:
      - PG_HOST=172.17.0.1
    volumes:
      - ~/.ssh:/home/nozich/.ssh:ro
      - ./:/home/nozich/app
    working_dir: /home/nozich/app
    # command: 'pnpm install --prod --frozen-lockfile --recursive && pnpm start ./ bomonti-${ENV}'
    command: 'pnpm start'
